"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class lcm_float32(object):
    __slots__ = ["data"]

    __typenames__ = ["float"]

    __dimensions__ = [None]

    def __init__(self):
        self.data = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(lcm_float32._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">f", self.data))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcm_float32._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcm_float32._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = lcm_float32()
        self.data = struct.unpack(">f", buf.read(4))[0]
        return self
    _decode_one = staticmethod(_decode_one)

    def _get_hash_recursive(parents):
        if lcm_float32 in parents: return 0
        tmphash = (0x856e135c782a36e9) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if lcm_float32._packed_fingerprint is None:
            lcm_float32._packed_fingerprint = struct.pack(">Q", lcm_float32._get_hash_recursive([]))
        return lcm_float32._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcm_float32._get_packed_fingerprint())[0]

